### ISSUE TITLE
催更

### ISSUE THREAD

**Issue by Asterecho** [ShiinaManatsu/PMXWindowsShellExtensions#1]
催更

**Comment by ShiinaManatsu** [comment]
给之前提交的东西打了个包, 快试试(

**Comment by Asterecho** [comment]
非常好用
![2022-11-13 12-37-54](https://user-images.githubusercontent.com/40272885/201506000-aad3d736-da80-4466-898e-b0fb5c623ae9.png)

**Comment by Asterecho** [comment]
大大，Quicklook插件能不能也更新下

**Comment by ShiinaManatsu** [comment]
> 大大，Quicklook插件能不能也更新下

其实我也用的很少, 重装系统后甚至没想起来还有 Quicklook 的插件(
